# Generated by Django 5.0.2 on 2024-03-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffet',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='buffets', to='food_reservation.organization'),
            preserve_default=False,
        ),
    ]
