# Generated by Django 5.0.2 on 2024-03-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0002_buffet_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationadmin',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='food_reservation.organization'),
        ),
    ]
