# Generated by Django 5.0.2 on 2024-04-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0004_organizationmembershipinvitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buffet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='food_reservation.buffet')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('time', models.TimeField()),
                ('dailyMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='food_reservation.dailymenu')),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('number_in_stock', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_reservation.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_reservation.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='food_reservation.client')),
                ('meal_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='food_reservation.mealfood')),
            ],
        ),
    ]
