# Generated by Django 5.0.2 on 2024-05-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0005_food_dailymenu_meal_mealfood_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Very Good')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buffet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='food_reservation.buffet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='food_reservation.client')),
            ],
        ),
    ]
