# Generated by Django 5.0.2 on 2024-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0007_client_wallet_dailymenu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
