# Generated by Django 5.0.2 on 2024-05-31 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0007_client_wallet_dailymenu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='buffet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menerfer', to='food_reservation.buffet'),
        ),
    ]
