# Generated by Django 5.0.2 on 2024-06-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0008_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealfood',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_reservation.meal'),
        ),
    ]
