# Generated by Django 5.0.2 on 2024-05-31 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0008_alter_dailymenu_buffet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='buffet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='food_reservation.buffet'),
        ),
    ]
