# Generated by Django 5.0.2 on 2024-06-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0010_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='buffet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='food_reservation.buffet'),
        ),
    ]
