# Generated by Django 5.0.2 on 2024-06-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0009_alter_food_description'),
        ('food_reservation', '0011_reserve_buffet'),
    ]

    operations = [
    ]
