# Generated by Django 5.0.2 on 2024-06-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_reservation', '0012_merge_0009_alter_food_description_0011_reserve_buffet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='wallet',
        ),
    ]
