# Generated by Django 5.0.2 on 2024-03-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
