# Generated by Django 5.0.2 on 2024-05-16 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_verified_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 15, 46, 20, 810907, tzinfo=datetime.timezone.utc)),
        ),
    ]
