# Generated by Django 5.0.2 on 2024-05-16 16:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_emailverification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 16, 21, 36, 690524, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ForgetPasswordVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('expire_at', models.DateTimeField(default=datetime.datetime(2024, 5, 16, 16, 21, 36, 690850, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forget_password_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
