# Generated by Django 5.0.2 on 2024-05-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_emailverification_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forgetpasswordverification',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
