# Generated by Django 5.0.2 on 2024-05-31 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_emailverification_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 8, 50, 50, 993993, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpasswordverification',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 8, 50, 50, 993993, tzinfo=datetime.timezone.utc)),
        ),
    ]
