version: '3.9'
services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile 
    command: ./docker/docker-entrypoint.sh
    ports:
      - 8000:8000
  
    restart: always
    volumes:
      - ../:/app
      - /var/www/ghablameh/media:/var/www/ghablameh/media
      - /var/www/ghablameh/static:/var/www/ghablameh/static
    depends_on:
    - db

  db:
      image: postgres:16

      env_file:
        - .env

      restart: always

      volumes:
        - postgres_data:/var/lib/postgresql/data/ 
      ports:
        - "5432:5432"


volumes:
  postgres_data:
  pg_data: 