# Generated by Django 5.0.2 on 2024-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_remove_payment_wallet_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
