name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Build Docker images
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: 'root' 
          key: ${{ secrets.SERVER_SSH_KEY }} 
          port: 2024
          script: | 
            cd /root/projects/nagzap/ghablameh
            git pull origin main
            docker-compose -f docker/docker-compose.yaml build 

      - name: Run tests
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: 'root' 
          key: ${{ secrets.SERVER_SSH_KEY }} 
          port: 2024
          script: | 
            cd /root/projects/nagzap/ghablameh
            docker-compose -f docker/docker-compose.yaml run --rm web pytest

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: 'root' 
          key: ${{ secrets.SERVER_SSH_KEY }} 
          port: 2024
          script: | 
            cd /root/projects/nagzap/ghablameh
            git pull origin main
            docker-compose -f docker/docker-compose.yaml up -d  
